language: objective-c
osx_image: xcode12

install: 
 - sudo easy_install cpp-coveralls

script:
 - xcodebuild -project DTCoreText.xcodeproj -scheme DemoApp build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO | xcpretty -s
 - xcodebuild -project DTCoreText.xcodeproj -scheme "DTCoreText (iOS)" build test -sdk iphonesimulator | xcpretty -s
 - xcodebuild -project DTCoreText.xcodeproj -scheme "DTCoreText (Mac)" build | xcpretty -s

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
